config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  get '/facebook_friends' => 'home#facebook_friends'

  root to: "home#show"

end

app/models/user.rb
class User < ActiveRecord::Base


	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.provider = auth.provider 
	    user.uid      = auth.uid
	    user.name     = auth.info.name
	    user.save
	  end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end

  def facebook_friends
  	@graph = Koala::Facebook::API.new(params[:oauth_access_token])
  	@friends = @graph.get_connections("me", "friends")
  	if @friends.blank?
  		flash[:error] = "Currently you don't have any frinds who join your app"
  	else
  		@friends
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	fb_info = env["omniauth.auth"]
    user = User.from_omniauth(fb_info)
    session[:user_id] = user.id
    redirect_to facebook_friends_path(:oauth_access_token => fb_info["credentials"]["token"])
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/facebook_friends.html.erb
<% @friends.each do |friend| %>
	<%= friend.name %>
	<br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facebook Auth Example</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div>
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>
</div>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<form action="#" id="login-form">
  <div class="heading">Login to My app</div>
  <br>
  <div class="right">
     <a href="">Connect with facebook</a> 
  </div>
</form>  